JavaScript localStorage in Elm
Elm Eugene
Wednesday, May 9, 2018, 5:30pm PDT
Bill St. Clair <billstclair@gmail.com>
[[https://www.meetup.com/Elm-Eug/events/vcjrhpyxhbmb/][www.meetup.com/Elm-Eug/events/vcjrhpyxhbmb]]
[[https://lisplog.org/localstorage/presentation.org][lisplog.org/localstorage/presentation.org]]
[[https://github.com/billstclair/elm-localstorage-presentation][github.com/billstclair/elm-localstorage-presentation]]

* Org mode

This is an Emacs Org Mode buffer. Many features
will be missing if you don't have Emacs.

* Setup

To be done before the presentation.

cd ~/elm-localstorage/example
elm reactor

Open a new window in Chrome. Hide the others.
Make the default font bigger.
  chrome://settings/fonts

http://localhost:8000

* Intro

You often need to have persistent state for your
Elm apps. I've found the easiest way to do this is
with the JavaScript [[https://html.spec.whatwg.org/multipage/webstorage.html#storage-2][localStorage]] facility.

localStorage.getItem(<name>)
localStorage.setItem(<name>, <value>)
localStorage.removeItem(<name>)
localStorage.length
localStorage.key(<index>)
localStorage.clear()

localStorage provides a persistent key/value store
for strings, with a separate database for each
domain.

* billstclair/elm-localstorage

[[http://package.elm-lang.org/packages/billstclair/elm-localstorage/latest][billstclair/elm-localstorage]] provides a simple
port-based interface from Elm to JS
localStorage. There is a pure-Elm, Dict-based
version that you can use in elm-reactor, and a
tiny JS file that you can attach to your
index.html file for real persistence.

Peruse docs for LocalStorage and
LocalStorage.SharedTypes.

* Code

[[https://github.com/billstclair/elm-localstorage/blob/4.0.2/example/PortExample.elm][example/PortExample.elm]]
[[https://github.com/billstclair/elm-localstorage/blob/4.0.2/example/SharedUI.elm][example/SharedUI.elm]]
[[https://github.com/billstclair/elm-localstorage/blob/4.0.2/site/index.html][site/index.html]]
[[https://github.com/billstclair/elm-localstorage/blob/4.0.2/site/js/ElmLocalStoragePorts.js][site/js/ElmLocalStoragePorts.js]]

* Demo

https://lisplog.org/localstorage

Right-click, Inspect
Application tab
LocalStorage/https︓//lisplog.org

* Elm Reactor Version

[[https://github.com/billstclair/elm-localstorage/blob/4.0.2/example/ReactorExample.elm][example/ReactorExample.elm]].

http://localhost:8000

* Stories

Nate asked me to share some stories. Here are a
few ideas. Pick one.

[[https://en.wikipedia.org/wiki/Joseph_Weizenbaum][Joseph Weisenbaum]]: mercury delay-line memory.
Creator of [[https://en.wikipedia.org/wiki/ELIZA][ELIZA]]. "m-x doctor" in Emacs.

[[https://en.wikipedia.org/wiki/Teletype_Model_33][TTY-33]] connected to Xerox Sigma 7 at UW in 1972.

TTY-33 connected to custom microcoded machine at
MIT in 1975. Seven-state UART, clocked at four
times BAUD rate.

Information hiding, the fundamental principle of
good software. Learned it at my first job out of
college in 1978, writing RatFor on PDP-11 under
RT-11.

* Local Variables

# Local Variables:
# fill-column: 50
# eval: (progn (text-scale-set 4) (auto-fill-mode))
# End:
